// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoMuAvWra-LQZJb4IPqDHUC7iUmTSBtho',
    appId: '1:848230535804:web:107a613fa8a4e31d766ff9',
    messagingSenderId: '848230535804',
    projectId: 'taco-2024',
    authDomain: 'taco-2024.firebaseapp.com',
    storageBucket: 'taco-2024.appspot.com',
    measurementId: 'G-F18CXD0WMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBYmpHRqDtt1mIm6USyES0MPCjVdtIpn4',
    appId: '1:848230535804:android:dd55bf8a0a17fe36766ff9',
    messagingSenderId: '848230535804',
    projectId: 'taco-2024',
    storageBucket: 'taco-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6pH1VEI26TDkOUO58TG4vYfTPO77p0hY',
    appId: '1:848230535804:ios:c4127da58e3513ba766ff9',
    messagingSenderId: '848230535804',
    projectId: 'taco-2024',
    storageBucket: 'taco-2024.appspot.com',
    iosBundleId: 'com.example.Taco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6pH1VEI26TDkOUO58TG4vYfTPO77p0hY',
    appId: '1:848230535804:ios:c4127da58e3513ba766ff9',
    messagingSenderId: '848230535804',
    projectId: 'taco-2024',
    storageBucket: 'taco-2024.appspot.com',
    iosBundleId: 'com.example.Taco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoMuAvWra-LQZJb4IPqDHUC7iUmTSBtho',
    appId: '1:848230535804:web:1b6c5581baf52124766ff9',
    messagingSenderId: '848230535804',
    projectId: 'taco-2024',
    authDomain: 'taco-2024.firebaseapp.com',
    storageBucket: 'taco-2024.appspot.com',
    measurementId: 'G-8Y0HBVDZ7Z',
  );
}
